#ifndef MINIMALIST_BLOCK_CHAIN_SYSTEM_SRC_UTILS_CONSTANTS_H
#define MINIMALIST_BLOCK_CHAIN_SYSTEM_SRC_UTILS_CONSTANTS_H

#include <stdbool.h>

#define VERBOSE true
#define TOTAL_NUMBER_OF_COINS 4096
#define LOG_TIME_FORMAT "%Y-%m-%d %H:%M:%S"
#define LOG_TIME_LENGTH 26

#endif
