#ifndef MINIMALIST_BLOCK_CHAIN_SYSTEM_SRC_UTILS_CONSTANTS_H
#define MINIMALIST_BLOCK_CHAIN_SYSTEM_SRC_UTILS_CONSTANTS_H

#include <stdbool.h>
#include "utils/log_utils.h"

#define VERBOSE true
#define PERSISTENCE_MODE PERSISTENCE_MYSQL
#define PERSISTENCE_MYSQL 1
#define PERSISTENCE_RAM 0
#define LOG_LEVEL LOG_INFO
#define TOTAL_NUMBER_OF_COINS 40960
#define LOG_TIME_FORMAT "%Y-%m-%d %H:%M:%S"
#define LOG_TIME_LENGTH 26

#endif
